"""Final updates

Revision ID: f26ca0c28564
Revises: de3b68567ed7
Create Date: 2023-12-22 18:11:54.303466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26ca0c28564'
down_revision = 'de3b68567ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_type', sa.String(length=10), nullable=True))
        batch_op.drop_column('is_available')

    with op.batch_alter_table('instructor', schema=None) as batch_op:
        batch_op.alter_column('course_assigned',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('day',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('day',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('instructor', schema=None) as batch_op:
        batch_op.alter_column('course_assigned',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('class_type')

    op.drop_table('availability')
    # ### end Alembic commands ###
